
-- 회원정보 번호 시퀀스 생성
CREATE SEQUENCE SEQ_MEM_INFO START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
-- 공통구분 번호 시퀀스 생성
CREATE SEQUENCE SEQ_GUBUN START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
-- 게시판 번호 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
-- 게시판 댓글 시퀀스 생성
CREATE SEQUENCE SEQ_BD_REPL START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
-- 게시판 첨부 시퀀스 생성
CREATE SEQUENCE SEQ_BD_FILE START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;

-- 회원정보 입력
INSERT INTO MEM_INFO(MEM_SID, MEM_ID, MEM_PW, MEM_NICK, MEM_REGI, MEM_UPDT, MEM_BL, MEM_GRADE)
VALUES(SEQ_MEM_INFO.NEXTVAL, 'bellabella1130@naver.com', '1111@', 'MOON', SYSDATE, SYSDATE, 'N', '9');

SELECT *
FROM MEM_INFO;

-- 공통구분 입력
INSERT INTO GUBUN(GUBUN_SID, GUBUN_CATE, GUBUN_DETAIL, GUBUN_REGI, GUBUN_UPDT)
VALUES(SEQ_GUBUN.NEXTVAL, '게시판', '자유게시판', SYSDATE, SYSDATE);

SELECT *
FROM GUBUN;

-- 게시글 입력
INSERT INTO BOARD(BD_SID, BD_GRP_SID, BD_GRP_LV, BD_GRP_DEP, GUBUN_SID, BD_TITLE, BD_CONT, BD_REGI, BD_UPDT, BD_CLI, BD_DELCK, BD_LIKE, BD_BLCK, MEM_SID)
VALUES(SEQ_BOARD.NEXTVAL, 1, 1, 0, 1, '제목 테스트', '내용 테스트', SYSDATE, SYSDATE, 0, 'N', 5, 0, 1);

INSERT INTO BOARD(BD_SID, BD_GRP_SID, BD_GRP_LV, BD_GRP_DEP, GUBUN_SID, BD_TITLE, BD_CONT, BD_REGI, BD_UPDT, BD_CLI, BD_DELCK, BD_LIKE, BD_BLCK, MEM_SID)
VALUES(SEQ_BOARD.NEXTVAL, 1, 2, 1, 1, 'RE: 제목 테스트', '내용 테스트', SYSDATE, SYSDATE, 0, 'N', 0, 0, 1);

INSERT INTO BOARD(BD_SID, BD_GRP_SID, BD_GRP_LV, BD_GRP_DEP, GUBUN_SID, BD_TITLE, BD_CONT, BD_REGI, BD_UPDT, BD_CLI, BD_DELCK, BD_LIKE, BD_BLCK, MEM_SID)
VALUES(SEQ_BOARD.NEXTVAL, 1, 3, 2, 1, 'RE: RE: 제목 테스트', 'RE: RE: 내용 테스트', SYSDATE, SYSDATE, 0, 'N', 0, 0, 1);

INSERT INTO BOARD(BD_SID, BD_GRP_SID, BD_GRP_LV, BD_GRP_DEP, GUBUN_SID, BD_TITLE, BD_CONT, BD_REGI, BD_UPDT, BD_CLI, BD_DELCK, BD_LIKE, BD_BLCK, MEM_SID)
VALUES(SEQ_BOARD.NEXTVAL, 1, 4, 1, 1, 'RE: 2. 제목 테스트', 'RE: 2. 내용 테스트', SYSDATE, SYSDATE, 0, 'N', 0, 0, 1);

SELECT *
FROM BOARD;

SELECT SEQ_BOARD.NEXTVAL FROM DUAL;


-- 게시판 전체 목록 조회
SELECT ROW_NUMBER() OVER(ORDER BY BD_GRP_SID, BD_GRP_LV) AS "NUM"
    , BD_SID, BD_GRP_SID, BD_GRP_LV, BD_GRP_DEP, BD_TITLE
    , CASE TO_CHAR(SYSDATE, 'YYYYMMDD') WHEN TO_CHAR(BD_REGI, 'YYYYMMDD') THEN TO_CHAR(BD_REGI, 'HH24:MI')
        ELSE TO_CHAR(BD_REGI, 'YY.MM.DD')
        END AS "BD_REGI"
    , (SELECT COUNT(*) FROM BD_REPL B WHERE B.BD_SID = A.BD_SID) AS "REPLCOUNT"
    , BD_CLI, BD_DELCK
    , (SELECT MEM_NICK FROM MEM_INFO A WHERE A.MEM_SID = MEM_SID) AS "MEM_NICK"
    , MEM_SID, BD_LIKE, BD_BLCK
FROM BOARD A
WHERE ROWNUM < 10
ORDER BY BD_GRP_SID, BD_GRP_LV;


-- 게시판 상세 내역 조회
SELECT BD_SID, BD_TITLE
    , (SELECT MEM_NICK FROM MEM_INFO A WHERE A.MEM_SID = MEM_SID) AS "MEM_NICK"
    , BD_CLI
    , BD_LIKE
    , TO_CHAR(BD_REGI, 'YYYY.MM.DD HH24:MI') AS "BD_REGI"
    , BD_CONT
    , (SELECT COUNT(*) FROM BD_REPL B WHERE B.BD_SID = 3) AS "REPLCOUNT"
FROM BOARD
WHERE BD_SID = 3;

SELECT *
FROM BOARD;

DESC BOARD;


-- 댓글 입력
INSERT INTO BD_REPL(REPL_SID, REPL_GRP, REPL_LV, REPL_DEPT, REPL_CONT, REPL_REGI, REPL_UPDT, REPL_DELCK, REPL_BLCK, BD_SID, MEM_SID)
VALUES(SEQ_BD_REPL.NEXTVAL, 1, 1, 0, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.', SYSDATE, SYSDATE, 'N', 0, 1, 1);
INSERT INTO BD_REPL(REPL_SID, REPL_GRP, REPL_LV, REPL_DEPT, REPL_CONT, REPL_REGI, REPL_UPDT, REPL_DELCK, REPL_BLCK, BD_SID, MEM_SID)
VALUES(SEQ_BD_REPL.NEXTVAL, 1, 4, 0, 'Dolorem tempore commodi atque ipsa repudiandae debitis sapiente molestiae quam dicta non quasi corporis amet maiores?', SYSDATE, SYSDATE, 'N', 0, 1, 1);
INSERT INTO BD_REPL(REPL_SID, REPL_GRP, REPL_LV, REPL_DEPT, REPL_CONT, REPL_REGI, REPL_UPDT, REPL_DELCK, REPL_BLCK, BD_SID, MEM_SID)
VALUES(SEQ_BD_REPL.NEXTVAL, 1, 2, 1, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.', SYSDATE, SYSDATE, 'N', 0, 1, 1);
INSERT INTO BD_REPL(REPL_SID, REPL_GRP, REPL_LV, REPL_DEPT, REPL_CONT, REPL_REGI, REPL_UPDT, REPL_DELCK, REPL_BLCK, BD_SID, MEM_SID)
VALUES(SEQ_BD_REPL.NEXTVAL, 1, 3, 2, 'tempore voluptas nesciunt blanditiis facilis inventore dignissimos maxime necessitatibus cupiditate nostrum.', SYSDATE, SYSDATE, 'N', 0, 1, 1);



-- 댓글 조회
SELECT REPL_SID, REPL_GRP, REPL_LV, REPL_DEPT, REPL_CONT
    , CASE TO_CHAR(SYSDATE, 'YYYYMMDD') WHEN TO_CHAR(REPL_REGI, 'YYYYMMDD') THEN TO_CHAR(REPL_REGI, 'HH24:MI')
        ELSE TO_CHAR(REPL_REGI, 'YY.MM.DD')
        END AS "REPL_REGI"
    , REPL_DELCK, REPL_BLCK, BD_SID
    , (SELECT MEM_NICK FROM MEM_INFO WHERE MEM_SID = A.MEM_SID) AS "MEM_NICK"
    , MEM_SID
FROM BD_REPL A
WHERE BD_SID = 1
ORDER BY REPL_LV;






